CREATE TABLE IF NOT EXISTS users
(
    id         INT PRIMARY KEY AUTO_INCREMENT,
    login      VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated    TIMESTAMP    DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
    last_login TIMESTAMP    DEFAULT '0000-00-00 00:00:00',
    2fa_token  VARCHAR(255) DEFAULT NULL
) DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_520_ci;